version: "3.8"

services:
  app:
    build:
      context: ./app
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: "sqlite:latest"
    volumes:
      - ./data:/data
