version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_ENV=production
    volumes:
      - ./data:/app/data
    depends_on:
      - db
  db:
    image: "sqlite:latest"
    volumes:
      - ./data:/data

# Carregar variáveis de ambiente do arquivo .env
env_file:
  - .env
